# Generated by Django 5.2.10 on 2026-03-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='free_posts_remaining',
            field=models.IntegerField(default=5),
        ),
    ]
