# Generated by Django 5.2.10 on 2026-02-03 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('fs', 'For Sale'), ('srv', 'Services'), ('gig', 'Gigs'), ('job', 'Jobs')], default='fs')),
                ('price', models.FloatField()),
                ('subcategory', models.CharField(choices=[('antiques', 'Antiques'), ('appliances', 'Appliances'), ('arts+crafts', 'Arts Crafts'), ('atv/utv/sno', 'Atv'), ('auto parts', 'Auto Parts'), ('aviation', 'Aviation'), ('baby+kid', 'Baby Kid'), ('barter', 'Barter'), ('beauty+hlth', 'Beauty Hlth'), ('bike parts', 'Bike Parts'), ('bikes', 'Bikes'), ('boat parts', 'Boat Parts'), ('boats', 'Boats'), ('books', 'Books'), ('business', 'Business'), ('cars+trucks', 'Cars Trucks'), ('cds/dvd/vhs', 'Cds'), ('cell phones', 'Cell Phones'), ('clothes+acc', 'Clothes Acc'), ('collectibles', 'Collectibles'), ('computer parts', 'Computer Parts'), ('computers', 'Computers'), ('electronics', 'Electronics'), ('farm & garden', 'Farm Garden'), ('free', 'Free'), ('furniture', 'Furniture'), ('garage sale', 'Garage Sale'), ('general', 'General'), ('heavy equip', 'Heavy Equip'), ('household', 'Household'), ('jewelry', 'Jewelry'), ('materials', 'Materials'), ('motorcycle parts', 'Motorcycle Parts'), ('motorcycles', 'Motorcycles'), ('music instr', 'Music Instr'), ('photo+video', 'Photo Video'), ('rvs+camp', 'Rvs Camp'), ('sporting', 'Sporting'), ('tickets', 'Tickets'), ('tools', 'Tools'), ('toys+games', 'Toys Games'), ('trailers', 'Trailers'), ('video gaming', 'Video Gaming'), ('wanted', 'Wanted'), ('wheels+tires', 'Wheels Tires')], default='general')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('city', models.CharField(max_length=128)),
            ],
        ),
    ]
