# Generated by Django 5.2.10 on 2026-02-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='listing/default.jpg', upload_to='listing/'),
        ),
    ]
