# Generated by Django 5.2.10 on 2026-02-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_listing_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
    ]
