# Generated by Django 5.2.10 on 2026-02-09 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_listing_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='subcategory',
            field=models.CharField(choices=[('antiques', 'Antiques'), ('appliances', 'Appliances'), ('arts+crafts', 'Arts Crafts'), ('atv+utv+sno', 'Atv'), ('auto+parts', 'Auto Parts'), ('aviation', 'Aviation'), ('baby+kid', 'Baby Kid'), ('barter', 'Barter'), ('beauty+hlth', 'Beauty Hlth'), ('bike+parts', 'Bike Parts'), ('bikes', 'Bikes'), ('boat+parts', 'Boat Parts'), ('boats', 'Boats'), ('books', 'Books'), ('business', 'Business'), ('cars+trucks', 'Cars Trucks'), ('cds+dvd+vhs', 'Cds'), ('cell+phones', 'Cell Phones'), ('clothes+acc', 'Clothes Acc'), ('collectibles', 'Collectibles'), ('computer+parts', 'Computer Parts'), ('computers', 'Computers'), ('electronics', 'Electronics'), ('farm+garden', 'Farm Garden'), ('free', 'Free'), ('furniture', 'Furniture'), ('garage+sale', 'Garage Sale'), ('general', 'General'), ('heavy+equip', 'Heavy Equip'), ('household', 'Household'), ('jewelry', 'Jewelry'), ('materials', 'Materials'), ('motorcycle+parts', 'Motorcycle Parts'), ('motorcycles', 'Motorcycles'), ('music+instr', 'Music Instr'), ('photo+video', 'Photo Video'), ('rvs+camp', 'Rvs Camp'), ('sporting', 'Sporting'), ('tickets', 'Tickets'), ('tools', 'Tools'), ('toys+games', 'Toys Games'), ('trailers', 'Trailers'), ('video+gaming', 'Video Gaming'), ('wanted', 'Wanted'), ('wheels+tires', 'Wheels Tires')], default='general'),
        ),
    ]
