# Generated by Django 5.2.10 on 2026-02-25 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketplace.conversation'),
        ),
    ]
