# Generated by Django 5.2.10 on 2026-03-29 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_remove_reply_conversation_reply_recipient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='listing',
            name='phone',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
