# Generated by Django 5.2.10 on 2026-04-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_listing_email_listing_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='was_read',
            new_name='was_read_by_recipient',
        ),
        migrations.AddField(
            model_name='reply',
            name='was_read_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
