# Generated by Django 5.2.10 on 2026-04-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_remove_listing_image_alter_listing_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='paid_for',
            field=models.BooleanField(default=False),
        ),
    ]
