# Generated by Django 5.2.10 on 2026-04-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0013_listing_paid_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='blog/%Y/%m/%d/'),
        ),
    ]
