# Generated by Django 5.2.10 on 2026-04-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_alter_listingimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listingimage',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='listings/%Y/%m/%d/'),
        ),
    ]
